CREATE DATABASE Finalll_Covid;
USE Finalll_Covid;

CREATE TABLE `User` (
`User_ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
`Name` VARCHAR(40) NOT NULL,
`Email` VARCHAR(30) NOT NULL UNIQUE,
`Region` VARCHAR(15) NOT NULL,
`Password` VARCHAR(10) NOT NULL UNIQUE,
`Confirm_Password` VARCHAR(10) NOT NULL UNIQUE,
`Contact` INT NOT NULL
);

CREATE TABLE `Login` (
`Email` VARCHAR(30) NOT NULL UNIQUE,
`Password` VARCHAR(10) NOT NULL UNIQUE,
`User_ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `Statistics` (
`No_Of_Positive_Cases` INT NOT NULL,
`No_Of_Death_Cases` INT NOT NULL,
`No_Of_Recovered_Cases`  INT NOT NULL,
`Number_of_Males` INT NOT NULL,
`Number_of_Females` INT NOT NULL,
`Date` DATE NOT NULL, 
`Region` VARCHAR(15) NOT NULL,
`Stat_ID` INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
`User_ID` INT NOT NULL, 
FOREIGN KEY (User_ID) REFERENCES User(User_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
